#!/usr/bin/env python3
"""Execute ONE counterfactual replacement point (docs/design_counterfactual.md).

Arms:
  frontier_resample: step `--at-step` is re-generated by the frontier model
                     under the frozen config (paired control).
  local_replace:     step `--at-step` is generated by --edit-model; steps after
                     it resume with the frontier model (protocol §0.3.5).

State recovery = scheme A: messages rebuilt byte-exact from the parent trace;
parent step scripts re-executed in a fresh nobody-sandbox workdir.

Env: FRONTIER_API_KEY / FRONTIER_BASE_URL must be set (batch scripts source
/data/lab/.verifront_env first).
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path
from uuid import uuid4

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from verifront.agents.base import load_models_config  # noqa: E402
from verifront.agents.codeact import (CodeActConfig,  # noqa: E402
                                      client_from_config)
from verifront.agents.openai_compat import OpenAICompatClient  # noqa: E402
from verifront.cf.replay import (extract_generated_steps,  # noqa: E402
                                 rebuild_messages, replay_prefix)
from verifront.sab.adapter import (SabTaskPaths,  # noqa: E402
                                   build_task_spec, chown_workdir,
                                   get_task, load_verified_tasks,
                                   prepare_workdir, run_eval)

BENCHMARK_ROOT_DEFAULT = Path("/data/lab/sab_data/benchmark_verified")
PARQUET_DEFAULT = Path("/data/lab/sab_data/verified.parquet")
PYTHON_BIN_DEFAULT = "/root/.local/share/mamba/envs/testbed/bin/python"


def git_commit() -> str:
    import subprocess
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=str(ROOT),
                              capture_output=True, text=True, timeout=10).stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--parent-run", required=True, help="runs/sab_<id>/frontier/<stamp>")
    ap.add_argument("--at-step", type=int, required=True)
    ap.add_argument("--arm", choices=["frontier_resample", "local_replace"], required=True)
    ap.add_argument("--edit-model", default=None)
    ap.add_argument("--edit-model-snapshot", default="")
    ap.add_argument("--python-bin", default=PYTHON_BIN_DEFAULT)
    ap.add_argument("--workdir-root", default="/tmp/vf_work")
    ap.add_argument("--artifacts-root", default=str(ROOT / "runs"))
    args = ap.parse_args()

    parent = Path(args.parent_run)
    parent_result = json.loads((parent / "result.json").read_text())
    instance_id = int(parent_result["instance_id"])

    df = load_verified_tasks(PARQUET_DEFAULT)
    row = get_task(df, instance_id)
    eval_script = str(row["eval_script_name"])

    cfg = load_models_config(ROOT / "configs" / "models.yaml")
    frontier_client = client_from_config(ROOT / "configs" / "models.yaml", "frontier")
    edit_client = None
    if args.arm == "local_replace":
        if not args.edit_model:
            raise SystemExit("--edit-model required for local_replace")
        edit_client = OpenAICompatClient(
            base_url=frontier_client.base_url,
            model=args.edit_model,
            api_key=os.environ.get("FRONTIER_API_KEY", ""),
        )
        edit_client.snapshot = args.edit_model_snapshot

    spec = build_task_spec(row, instance_id)
    config = CodeActConfig(
        max_steps=12, step_timeout_s=300.0, max_tokens=8192,
        python_bin=args.python_bin,
    )

    stamp = f"cf{int(time.time())}-{os.getpid()}"
    out_dir = Path(args.artifacts_root) / f"sab_{instance_id}" / f"cf_{args.arm}" / stamp
    out_dir.mkdir(parents=True, exist_ok=True)

    task_dir = Path(args.workdir_root) / f"sab_{instance_id}" / "cf"
    sandbox_dir = task_dir / uuid4().hex[:12]
    sandbox_dir.mkdir(parents=True, mode=0o751)
    vf_root = Path(args.workdir_root)
    if vf_root.is_dir():
        os.chmod(vf_root, 0o711)
    paths = SabTaskPaths(benchmark_root=BENCHMARK_ROOT_DEFAULT,
                         workdir=sandbox_dir / "wd")
    prepare_workdir(paths, row)
    chown_workdir(paths)

    from verifront.agents.codeact import CodeActAgent  # noqa: PLC0415
    agent = CodeActAgent(frontier_client, config, workdir=paths.workdir,
                         agent_commit=git_commit(), benchmark_version="sab-verified-c26e151")

    t0 = time.monotonic()
    fidelity = replay_prefix(parent, agent, args.at_step)
    if args.at_step > 1 and not fidelity["steps"]:
        print(json.dumps({"error": "no prefix steps replayed", "fidelity": fidelity}))
        return 1

    parent_steps = extract_generated_steps(parent)
    prefix_steps = [s for s in parent_steps if s["step_no"] < args.at_step]
    messages = rebuild_messages(spec, config, prefix_steps)

    def client_for_step(step_i: int):
        if step_i == args.at_step and edit_client is not None:
            return edit_client
        return frontier_client

    run = agent.run_from(spec, messages, start_step=args.at_step,
                         client_for_step=client_for_step)

    for p in sorted(paths.workdir.glob("step_*.py")):
        shutil.copy2(p, out_dir / p.name)
    traj = run.trajectory
    (out_dir / "trace.jsonl").write_text(traj.to_jsonl(), encoding="utf-8")
    ev = run_eval(paths, eval_script, args.python_bin)

    fr = cfg["frontier"]
    meta = {
        "instance_id": instance_id, "arm": f"cf_{args.arm}",
        "edit_step": args.at_step, "edit_model": args.edit_model,
        "edit_model_snapshot": args.edit_model_snapshot,
        "parent_run": str(parent), "parent_outcome": parent_result["eval_success"],
        "replay_fidelity": fidelity, "cf_status": run.status, "cf_steps": run.steps,
    }
    summary = {
        "instance_id": instance_id, "status": run.status,
        "eval_success": ev["success"], "eval_detail": ev["detail"],
        "token_usage": run.token_usage,
        "wall_s": round(time.monotonic() - t0, 3),
        "snapshot": fr["model_id"], "stamp": stamp, "cf_meta": meta,
    }
    (out_dir / "result.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"instance_id": summary["instance_id"], "status": summary["status"],
                      "eval_success": summary["eval_success"],
                      "eval_detail": summary["eval_detail"],
                      "edit_step": meta["edit_step"], "arm": summary["arm"] if "arm" in summary else meta["arm"],
                      "edit_model": meta["edit_model"]}, ensure_ascii=False))
    shutil.rmtree(sandbox_dir, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
